---
title: "Incidence: Daily and 14-Day Rolling Average, Calculated Daily"
author:
- name: Nicole Harty, MPH
  affiliation: Epidemiologist/Data Manager
date: "`r format(Sys.time(), '%B %d, %Y, %I %p')`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
    css: template.css
---

## Incidence: Daily and 14-Day Rolling Average, Calculated Daily  
**NOTE:** Cases are attributed to a date based upon test collection date, for those who have a test collection date. For those with missing test collection dates, the report date is used.   

```{r label=RollingIncidence14day}
plot_ly(ConfProbCases %>%
                    group_by(AttributionDate) %>%
                    summarise(NumberCases = n()) %>%
                    right_join(Calendar, by = c("AttributionDate" = "date")) %>%
                    replace(., is.na(.), 0) %>%
                    arrange(AttributionDate) %>%
                    filter(AttributionDate<=(params$DataThroughDate)) %>%
                    mutate(Case14da = zoo::rollsumr(NumberCases, k = 14, fill = NA)),
          x = ~AttributionDate,
          y = ~Case14da,
          type = "scatter",
          color = I("#4E2B1F"),
          mode = "lines",
          yaxis = "y",
          name = "Rolling 14-day Sum Cases by Specimen Collection Date") %>%
  layout(#title = "Cases per Day",
          margin = list(l=50,r=50,h=175),
         xaxis = list(type = 'date',
                      tickformat = "%b %d, %Y",
                      autotick = F, 
                      tickangle = 45,
                      tick0 = "2000-01-10",
                      dtick = 1209600000,
                      title = "Date (all listed dates are Mondays)",
                      showgrid = FALSE),
         yaxis = list(title = "14-day Rolling Sum",
                      showgrid = FALSE),
         # yaxis2 = list(
         #   tickfont = list(color = "#4E2B1F"),
         #   overlaying = "y",
         #   side = "right",
         #   showgrid = FALSE,
         #   title = "14-day Rolling Sum",
         #   rangemode = "tozero",
         #   range = c(0,588)),
         legend = list(orientation = 'h', y=-.3),
         font = list(family = "Arial", size = 12),
         shapes = list(
                list(type = "rect",
                    fillcolor = 'rgb(71, 118, 145)', line = list(color = 'rgb(71, 118, 145)'), opacity = 0.4,
                    x0 = 0, x1 = 1, xref = "paper",
                    y0 = 0, y1 = 52, yref = "y1"),
              list(type = "rect",
                    fillcolor = 'rgb(187, 70, 40)', line = list(color = 'rgb(187, 70, 40)'), opacity = 0.4,
                    x0 = 0, x1 = 1, xref = "paper",
                    y0 = 52, y1 = 256, yref = "y1"),
              list(type = "rect",
                    fillcolor = 'rgb(78, 43, 31)', line = list(color = 'rgb(78, 43, 31)'), opacity = 0.4,
                    x0 = 0, x1 = 1, xref = "paper",
                    y0 = 256, y1 = 400, yref = "y1")
              ),
          annotations = list(
           list(x = .18,
                y = 26,
                text = "Low Risk",
                xref = "paper",
                yref = 'y1',
                showarrow = FALSE,
                font = list(family = "Arial", size = 12, color = "#477691")),
           list(x = .18,
                y = 128,
                text = "Caution",
                xref = "paper",
                yref = 'y1',
                showarrow = FALSE,
                font = list(family = "Arial", size = 12, color = "#BB4628")),
           list(x = .18,
                y = 300,
                text = "High Risk",
                xref = "paper",
                yref = 'y1',
                showarrow = FALSE,
                font = list(family = "Arial", size = 12, color = "#4E2B1F")),
           list(x = .0,
                y = .5,
                text = "Data prepared by Routt County Public Health",
                xref = "paper",
                yref = 'paper',
                showarrow = FALSE,
                font = list(family = "Arial", size = 12, color = "gray"))
            )
         )
```
```{r label=NumberCasesperDay14day}
plot_ly(ConfProbCases %>%
          filter(#CountsTowardTotal=="Yes", 
                 AttributionDate<=(params$DataThroughDate)) %>%
          group_by(AttributionDate) %>%
          summarise(NumberCases = n()),
  x = ~AttributionDate,
  y = ~NumberCases,
  type = "bar",
  color = I("#BB4628"),
  name = "Daily Case") %>%
add_trace(data = (ConfProbCases %>%
                    group_by(AttributionDate) %>%
                    summarise(NumberCases = n()) %>%
                    right_join(Calendar, by = c("AttributionDate" = "date")) %>%
                    replace(., is.na(.), 0) %>%
                    arrange(AttributionDate) %>%
                    filter(AttributionDate<=(params$DataThroughDate)) %>%
                    mutate(Case14da = zoo::rollsumr(NumberCases, k = 14, fill = NA))),
          x = ~AttributionDate,
          y = ~Case14da,
          type = "scatter",
          color = I("#4E2B1F"),
          mode = "lines",
          yaxis = "y2",
          name = "Rolling 14-day Sum Cases by Specimen Collection Date") %>%
  layout(title = "Cases per Day with Rolling 14-day Incidence",
          margin = list(l=50,r=50,h=175),
         xaxis = list(type = 'date',
                      tickformat = "%b %d, %Y",
                      autotick = F, 
                      tickangle = 45,
                      tick0 = "2000-01-10",
                      dtick = 1209600000,
                      title = "Date (all listed dates are Mondays)"),
         yaxis = list(title = "Number of Cases",
                      showgrid = FALSE),
         yaxis2 = list(
           tickfont = list(color = "#4E2B1F"),
           overlaying = "y",
           side = "right",
           showgrid = FALSE,
           title = "14-day Rolling Sum",
           rangemode = "tozero",
           range = c(0,588)),
         legend = list(orientation = 'h', y=-.3),
         font = list(family = "Arial", size = 12),
         shapes = list(
                list(type = "rect",
                    fillcolor = 'rgb(71, 118, 145)', line = list(color = 'rgb(71, 118, 145)'), opacity = 0.4,
                    x0 = 0, x1 = 1, xref = "paper",
                    y0 = 0, y1 = 52, yref = "y2"),
              list(type = "rect",
                    fillcolor = 'rgb(187, 70, 40)', line = list(color = 'rgb(187, 70, 40)'), opacity = 0.4,
                    x0 = 0, x1 = 1, xref = "paper",
                    y0 = 52, y1 = 256, yref = "y2"),
              list(type = "rect",
                    fillcolor = 'rgb(78, 43, 31)', line = list(color = 'rgb(78, 43, 31)'), opacity = 0.4,
                    x0 = 0, x1 = 1, xref = "paper",
                    y0 = 256, y1 = 588, yref = "y2")
              ),
          annotations = list(
           list(x = .18,
                y = 26,
                text = "Low Risk",
                xref = "paper",
                yref = 'y2',
                showarrow = FALSE,
                font = list(family = "Arial", size = 12, color = "#477691")),
           list(x = .18,
                y = 128,
                text = "Caution",
                xref = "paper",
                yref = 'y2',
                showarrow = FALSE,
                font = list(family = "Arial", size = 12, color = "#BB4628")),
           list(x = .18,
                y = 400,
                text = "High Risk",
                xref = "paper",
                yref = 'y2',
                showarrow = FALSE,
                font = list(family = "Arial", size = 12, color = "#4E2B1F")),
           list(x = .0,
                y2 = .5,
                text = "Data prepared by Routt County Public Health",
                xref = "paper",
                yref = 'paper',
                showarrow = FALSE,
                font = list(family = "Arial", size = 12, color = "gray"))
            )
         )
```

